version: '3.1'

services:
  api:
    build: ./API
    ports:
      - 3001:3001
    environment:
      DB_HOST: cluster0.z7xjr.mongodb.net
      DB_NAME: test 
      DB_USER: loddrik
      DB_PASS: 1234
  front:
    build: ./recipe-app-1
    ports:
      - 3000:80
    depends_on:
      - api